Skeleton
js-tasks-ru/htmlcss-20220919_konstantin-biriukov pull request #10
Opened 2022-10-01 00:51 UTC by KonstantinBiryukov

Lecture 2. Skeleton solution

<details>
<img width="480" alt="Screen Shot 2022-09-30 at 7 50 52 PM" src="https://user-images.githubusercontent.com/38155183/193376609-626fc067-8ddd-4b37-93d3-22fd5ff3ceee.png">

2022-10-01 00:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-01 01:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 06:03 UTC, GSemikozov requested changes

2022-10-01 06:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 192px;
высоту тоже не стоит ограничивать по высоте (если решим добавить еще одну линию например)

2022-10-01 12:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-01 13:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-02 19:44 UTC, GSemikozov approved these changes

2022-10-02 19:44 UTC, merged