Input Form
js-tasks-ru/htmlcss-20220919_konstantin-biriukov pull request #24
Opened 2022-10-15 19:10 UTC by KonstantinBiryukov

Input type="text": 
default, 
focus, 
success, 
error, 
disabled

<details>
<img width="880" alt="Screen Shot 2022-10-15 at 2 10 35 PM" src="https://user-images.githubusercontent.com/38155183/196003981-e8d63461-761f-49dd-a12f-7b3f311067f0.png">

2022-10-15 19:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-16 22:20 UTC, GSemikozov requested changes

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <form class="form__group form__group_default">
form-group и использовать элемент form не надо

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <label class="form__group_label" for="default">Label</label>
form-group__label

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <div class="form__group_input-wrapper">
form-group__wrapper

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <input class="form__group_input" type="text" name="default" id="default" placeholder="Placeholder">
form-group__input

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <form class="form__group form__group_focus">
фокус описываем на урвоне инпута, есть встроенный псевдокласс, не надо пытаться оформить через класс

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <form class="form__group form__group_success">
form-group_success

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <svg class="form__group_icon icon_success" fill="none">
form-group__icon form-group__icon_success

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.form__inputs {
не часть блока input

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    height: 56px;
свойство инпута

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    height: 100%;
см выше

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    padding-left: 24px;
паддинги нужны со всех сторон

2022-10-16 22:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +::placeholder {
глобальные стили в компонентах не оформляем, поэтому form-group__input::placeholder

2022-10-17 01:02 UTC, KonstantinBiryukov commented on 07-lection5/04-input/input.css
> +.form__inputs {
Все же пришлось оставить этот враппер, без него не выходит сделать верстку общего вида инпутов, но я закинул этот css класс в отдельный файл.

2022-10-18 09:22 UTC, GSemikozov approved these changes

2022-10-18 09:22 UTC, merged