Inner-page: final
js-tasks-ru/htmlcss-20220919_konstantin-biriukov pull request #30
Opened 2022-10-28 04:57 UTC by KonstantinBiryukov

Inner Page - final;

<details>
<img width="1096" alt="Screen Shot 2022-10-27 at 11 56 08 PM" src="https://user-images.githubusercontent.com/38155183/198505975-11aa550a-6098-49c7-a281-51e7d2aa55f2.png">

2022-10-28 04:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-28 19:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-28 20:37 UTC, GSemikozov requested changes

2022-10-28 20:37 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__menu_open {
странный модификатор - говорит "open", а по факту - display: none). Кстати, блок называется burger-menu а не burger. Видимо какой-то старый неиспользуемый код?

2022-10-28 20:37 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__open {
это не часть блока .burger-menu, даже по структуре верстки видно

2022-10-28 21:22 UTC, KonstantinBiryukov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__menu_open {
да, спасибо, этот селектор уже не используется. удалил.

2022-10-28 21:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-28 21:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-28 21:44 UTC, KonstantinBiryukov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__open {
спасибо, пофиксил

2022-10-29 01:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-29 03:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-29 19:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-29 19:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-29 20:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-29 20:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-30 20:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-30 21:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-30 22:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-30 22:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-31 22:48 UTC, GSemikozov requested changes

2022-10-31 22:48 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip_preview {
что-то лишнее (внешнее позиционирование без понимания контекста)

2022-10-31 22:48 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar_preview {
и тут (хотя тут и попроще, можно оставить)

2022-10-31 22:48 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__input[id="html-tab"]:checked ~ .components__bottom .tabs__content_html,
.components__bottom - это не часть блока .tabs (если поменяем уровень вложенности или встроим другой компонент вместо .components - верстка развалится). Здесь нужно привязываться к элементам данного блока

2022-10-31 23:47 UTC, KonstantinBiryukov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip_preview {
Я так понимаю, что элемент нормально не центрируется потому что центрирование происходит по знаку вопросика, а не по всему элементу, поэтому пришлось воспользоваться хаком с translate. Класс убрал, перевел в инлайн стил.

2022-10-31 23:48 UTC, KonstantinBiryukov commented on components/tabs/tabs.css
> +.tabs__input[id="html-tab"]:checked ~ .components__bottom .tabs__content_html,
поправил

2022-11-01 00:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-04 00:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-09 16:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-10 21:27 UTC, GSemikozov approved these changes

2022-11-10 21:27 UTC, merged