Histogram
js-tasks-ru/htmlcss-20220919_konstantin-biriukov pull request #9
Opened 2022-09-30 23:39 UTC by KonstantinBiryukov

Lecture 2. Histogram task.

<details>
<img width="472" alt="Screen Shot 2022-09-30 at 6 39 40 PM" src="https://user-images.githubusercontent.com/38155183/193369601-3e6670b7-270e-4e24-b3f4-405f897040fb.png">

2022-09-30 23:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-01 06:02 UTC, GSemikozov requested changes

2022-10-01 06:02 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
лишнее, здесь лучше использовать свойства флекса flex-grow / flex-basis

2022-10-01 06:02 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0 1px;
отступ должен быть 1px поэтому можно только margin-right

2022-10-01 06:02 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.container {
сторонние стили в файле стилей конкретного блока описывать нельзя)
унесем в style хтмл страницы

2022-10-02 19:43 UTC, GSemikozov requested changes

2022-10-02 19:43 UTC, GSemikozov commented on components/container/container.css
> +.histogram__container {
это нам никогда не потребуется кроме как в самой задаче - так что лучше туда и унести)

2022-10-02 23:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 06:53 UTC, GSemikozov approved these changes

2022-10-03 06:54 UTC, merged